#+title: Uma introdução à Programação em Emacs Lisp
#+AUTHOR: Felipe Costa Canteiro
#+filetags: elisp:emacs:Code
#+date: [2026-06-15 seg]
#+export_file_name: ../html/elisp
#+options: date:nil num:nil
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/html-theme-readtheorg.setup
#+LANGUAGE: pt-br

* Prefácio
A maior parte do ambiente integrado GNU Emacs é escrita na linguagem de programação chamada Emacs Lisp. O código escrito nesta linguagem é o software - os conjuntos de instruções - que dizem ao computador o que fazer quando você dá comandos a ele. O Emacs é projetado de forma que você possa escrever novo código em Emacs Lisp e facilmente instalá-lo como uma extensão ao editor.

(GNU Emacs é, às vezes, chamado de um "editor extensível", mas ele faz muito mais do que prover capacidades de edição. É mais adequado se referir ao Emacs como um "ambiente de computação extensível". Porém, essa frase é comprida demais. É mais fácil se referir ao Emacs simplesmente como um editor. Além disso, tudo o que se faz no Emacs - encontrar a data Maia e fases da Lua, simplificar polinômios, depurar código, gerenciar arquivos, ler cartas, escrever livros - todas essas atividades são tipos de edição no sentido mais geral da palavra.)

+ [[*por que estudar emacs lisp?][Por que estudar Emacs Lisp?]]
+ [[*sobre a leitura deste texto][Sobre a leitura deste texto]]
+ [[*para quem isso foi escrito][Para quem isso foi escrito]]
+ [[*história do lisp][História do Lisp]]
+ [[*um adendo para novatos][Um adendo para novatos]]
+ [[*agradecimentos][Agradecimentos]]
** Por que estudar Emacs Lisp?
Apesar de geralmente associarem Emacs Lisp exclusivamente ao Emacs, ele é uma linguagem de programação completa. Você pode usar Emacs Lisp como você faria com qualquer outra linguagem de programação.

Talvez você queira entender programação; talvez você queira extender o Emacs; ou talvez você quer se tornar um programador. Essa introdução ao Emacs Lisp é projetada para te dar início: para te guiar em aprender os fundamentos da programação, e, mais importante, te mostrar como você pode se ensinar a ir além.

** Sobre a leitura deste texto
Ao longo deste documento, você verá pequenos "programas amostra" que você pode executar dentro do Emacs. Se você ler este documento em Info dentro do GNU Emacs, você pode executar os programas à medida que eles aparecem. De forma alternativa, você pode ler esta introdução como um livro impresso sentado próximo a um computador executando Emacs. (isso é o que gosto de fazer; eu gosto de livros impressos.) Se você não possui uma instância do Emacs em execução por perto, você ainda pode ler este texto, mas neste caso, é melhor tratar isso como um romance ou guia de viagem para um país ainda não visitado: interessante, mas não é a mesma coisa que estar lá.

Boa parte desta introdução é dedicada a orientações ou passeios guiados de código usado no GNU Emacs. Esses passeios são projetados com dois objetivos: primeiro, te familiarizar com código real e funcional (código que você utiliza todos os dias); e segundo, te familiarizar em como o Emacs funciona. É interessante ver como um ambiente funcional é implementado. Além disso, espero que você pegue o hábito de navegar através de código fonte. Você pode aprender com isso e minerar por ideias. Ter o GNU Emacs é como ter uma caverna do dragão cheia de tesouros.

Em adição a aprender sobre o emacs como um editor e o emacs lisp como uma linguagem de programação, os exemplos e passeios guiados vão te proporcionar uma oportunidade de se familiarizar com o Emacs como um ambiente de programação Lisp. o GNU Emacs suporta programação e provê ferramentas que você vai querer ficar confortável em utilizar, como ~M-.~ (a tecla que chama o commando ~xref-find-definitions~). Você também vai aprender sobre /buffers/ e outros objetos que são parte do ambiente. Aprender sobre essas funcionalidades do Emacs é como aprender novas rotas na sua cidade natal.

Finalmente, eu espero transmitir algumas das habilidades para utilizar o Emacs para aprender aspectos da programação que você não conhece. Você pode frequentemente utilizar o Emacs para te ajudar a entender o que te intriga ou para descobrir como fazer algo novo. Esta auto-dependência não é apenas prazerosa, mas uma vantagem.

** Para quem isso foi escrito
Esse texto foi escrito como uma introdução elementar para pessoas que não são programadoras. Se você é um programador, você pode não se satisfazer com este princípio. A razão é que você pode ter se tornado um especialista em ler manuais de referência e se desanimar com a forma que este texto é organizado.

Um programador expert que revisou este texto me disse:
#+begin_quote
Eu prefiro aprender através de manuais de referência. Eu "mergulho" em cada parágrafo, e "volto para respirar" entre os parágrafos.

Quando eu chego ao fim de um parágrafo, eu assumo que o assunto está finalizado, terminado, que eu sei tudo o que preciso (com a possível exceção do caso quando o próximo parágrafo começa falando sobre isso em mais detalhes). Eu espero que um manual de referência bem escrito não terá muita redundância, e que ele tera excelente indicações para um (único) lugar onde a informação que eu quero está.
#+end_quote

Essa introdução não foi escrita para esta pessoa!

Primeiramente, eu tento dizer tudo ao menos três vezes: primeiro, para introduzir isso; segundo, mostrar isso em contexto; e terceiro, para mostrar isso em um contexto diferente, ou revisar. 

Em segundo lugar, eu raramente vou colocar toda a informação sobre um assunto em um único lugar, muito menos em um parágrafo. Na minha forma de pensar, isso impõem um peso muito grande para o leitor. Ao invés disso, eu tento explicar apenas o que você precisa saber no momento. (Às vezes eu incluo um pouco de informação extra para que você não fique surpreso depois, quando a informação adicional é formalmente introduzida.)

Quando você ler este texto, não é esperado que você aprenda tudo na primeira vez. Frequentemente você terá apenas que ter um conhecimento superficial sobre alguns dos itens mencionados. Minha esperança é que eu tenha estruturado o texto e te dado dicas o suficiente para que você esteja alerta ao que é importante, e se concentrar nisso.

Este livro, /Uma Introdução à Programação em Emacs Lisp/, tem um documento associado, [[https://www.gnu.org/software/emacs/manual/html_mono/elisp.html#top][o Manual de Referência do GNU Emacs Lisp]], no /Manual de Referência do GNU Emacs Lisp/. O manual de referência possui mais detalhes do que esta introdução. No manual de referência, toda a informação sobre um tópico é concentrado em um único lugar. Você deve se direcionar a ele se é como o programador citado acima. E, é claro, depois de ler esta /introdução/, você vai achar o /Manual de Referência/ mais útil quando você estiver escrevendo seus próprios programas. 

** História do Lisp
Lisp foi desenvolvido inicialmente no fim da década de 1950 no Instituto de Tecnologia de Massachusetts (MIT) para pesquisa em inteligência artificial. O grande poder da linguagem Lisp faz com que seja também superior para outros propósitos, como escrever comandos de editor e ambientes integrados.

GNU Emacs Lisp é grandemente inspirado por Maclisp, que foi escrito no MIT na década de 1960. É, de certa forma, inspirado em Common Lisp, que se tornou um padrão na década de 1980. Porém, o Emacs Lisp é muito mais simples que o Common Lisp. (a distribuição padrão do Emacs contém um arquivo de extensão opcional, ~cl-lib.el~, que adiciona muitas funcionalidades do Common Lisp ao Emacs Lisp.)

** Um adendo para novatos
Se você não conhece o GNU Emacs, você ainda pode ler este documento de maneira proveitosa. Porém, recomendo que você aprenda sobre o Emacs, ainda que apenas para movimentar-se pela tela do seu computador. Você pode se ensinar a como utilizar o Emacs com o tutorial embutido. para utilizá-lo, digite ~C-h t~. (isto significa que você deve pressionar e liberar a tecla ~CTRL~ e o ~h~ ao mesmo tempo, e depois pressionar e liberar ~t~.)

Além disso, eu frequentemente me refiro para um dos comandos padrão do Emacs listando as teclas que você pressiona para executar o commando e depois dando o nome do commando entre parenteses, desta forma: ~C-M-\~ ~(indent region)~. Isto significa que o comando ~indent-region~ é geralmente executado ao digitar ~C-M\~. (Você pode, se desejar, mudar as teclas que são digitadas para evocar o comando; isto se chama /rebinding/. Veja [[*mapeamento de teclas][mapeamento de teclas]].) A abreviação ~C-M-\.~ significa que você digita a tecla ~CTRL~, a tecla ~META~ e a tecla ~\~ ao mesmo tempo. (Em muitos teclados modernos, a tecla ~META~ é chamada ~ALT~.) Às vezes uma combinação como essa é chamada acorde de teclas (/keychord/), já que é similar a como se toca um acorde em um piano. se seu teclado não possui uma tecla ~META~, a tecla ~ESC~ é utilizada no lugar. neste caso, ~C-M-\~ significa que você pressiona e libera sua tecla ~ESC~ e depois digite a tecla ~CTRL~ e a tecla ~\~ ao mesmo tempo. Porém, geralmente ~C-M-\~ significa pressionar a tecla ~CTRL~ junto com a tecla descrita como ~ALT~ e, ao mesmo tempo, pressionar a tecla ~\~.

Em adição a digitar um /keychord/ isolado, você pode prefixar o que digita com ~C-u~, chamado de /argumento universal/. O /keychord/ ~C-u~ passa um argumento para o comando subsequente. assim, para indentar uma região de texto em 6 espaços, selecione a região e pressione ~C-u 6 C-M-\~. (Se você não especificar um número, ou o Emacs passa o número 4 paro o comando ou executa o comando de maneira diferente do que faria de outra forma.) veja [[https://www.gnu.org/software/emacs/manual/html_mono/emacs.html#arguments][argumentos numéricos no /manual do gnu emacs/]].

Se você está lendo isso em info utilizando o GNU Emacs, você pode ler todo este documento apenas pressionando a tecla de espaço, ~SPC~. (para aprender sobre Info, digite ~C-h i~ e selecione Info.)

Um adendo sobre terminologia: quando utilizo à palavra Lisp sozinha, eu frequentemente estou me referindo aos vários dialetos Lisp em geral, mas quando eu digo sobre Emacs Lisp, me refiro particularmente ao GNU Emacs Lisp.

** Agradecimentos
Meus agradecimentos a todos que me ajudaram com este livro. Meus agradecimentos especiais a Jim Blandy, Noah Friedman, Jim Kingdon, Roland McGrath, Frank Ritter, Randy Smith, Richard M. Stallman, e Melissa Weisshaus. Meus agradecimentos vão também tanto para Philip Johnson como para David Stampe pelo seu encorajamento paciente. Meus erros são meus.

Robert J. Chassel bob@gnu.org

* Processamento de listas
Para um olhar não treinado, o Lisp é uma linguagem de programação estranha; Em código Lisp há parenteses em todo lugar. Alguns até dizem que o nome representa "Vários Parenteses Bobos Isolados" ("/Lots of Isolated Silly Parentheses/").
Mas dizer isso é injusto. Lisp representa Processamento de Listas (/LISt Processing/), e a linguagem de programação lida com /listas/ (e listas de listas) colocando-as entre parenteses.
Os parenteses marcam os limites da lista. Às vezes uma lista é precedida por um apóstrofo '/'/', chamado de /aspas simples/ (/single-quote/) em Lisp. Listas são a base do Lisp.

+ [[*Listas Lisp][Listas Lisp]]
+ [[*Execute um Programa][Execute um Programa]]
+ [[*Gere uma Mensagem de Erro][Gere uma Mensagem de Erro]]
+ [[*Nomes Símbolos e Definições de Funções][Nomes dos Símbolos e Definições de Funções]]
+ [[*O Interpretador Lisp][O Interpretador Lisp]]
+ [[*Avaliação][Avaliação]]
+ [[*Variáveis][Variáveis]]
+ [[*Argumentos][Argumentos]]
+ [[*Assinalando o Valor de uma Variável][Assinalando o Valor de uma Variável]]
+ [[*Resumo][Resumo]]
+ [[*Exercícios][Exercícios]]

** Listas Lisp
Em Lisp, uma lista se parece com isso: ~'(rosa violeta bem-me-quer bafo-de-boi)~. Esta lista é precedida por um único apóstrofo. Ela também poderia ser escrita da forma a seguir, que se parece mais com o tipo de lista que você deve estar acostumado:
#+begin_src emacs-lisp
'(rosa
  violeta
  bem-me-quer
  bafo-de-boi)
#+end_src

Os elementos desta lista são os nomes de 4 diferentes flores, separados um do outro por um espaço em branco e cercado por parenteses, como flores com uma parede de pedras em volta delas.

*** Números, Listas dentro de Listas
Listas também podem conter números, como nesta lista: ~(+ 2 2)~. Esta lista possui o sinal de adição '=+=', seguido de dois '2's, separados por um espaço em branco.

Em Lisp, tanto dados como programas são representados da mesma forma; assim, ambos são listas de palavras, números, ou outras listas, separados por um espaço em branco e cercado por parenteses. (Se um programa se parece com dados, um programa pode facilmente servir como dado para outro; esta é uma funcionalidade muito poderosa do Lisp.) (Aliás, essas duas observações entre parenteses /não são/ listas Lisp, porque elas contém ';' e '.' como pontuação.)

Aqui está uma outra lista, desta vez com uma lista dentro dela:

#+begin_src emacs-lisp
'(essa lista tem (uma lista dentro dela))
#+end_src

Os componentes desta lista são as palavras '=essa=', '=lista=', e a lista '=(uma lista dentro dela)=. A lista interior é composta das palavras '=uma=', '=lista=', '=dentro=', '=dela='. 

*** Átomos Lisp
Em Lisp, o que estávamos chamando de palavras são chamados /átomos/. Esse termo vem do significado histórico da palavra átomo, que significa "indivisível". Até onde o Lisp sabe, as palavras que nós viemos utilizando nas listas não podem ser divididas em qualquer partes menores e ainda significar a mesma coisa como parte de um programa; da mesma forma com números e símbolos de caracteres únicos como '=+='. Por outro lado, diferentemente de um átomo antigo, uma lista pode ser dividida em partes. (Veja [[*~car~, ~cdr~, ~cons~: funções fundamentais][~car~, ~cdr~, ~cons~: funções fundamentais]].)

Em uma lista, átomos são separados uns dos outros por um espaço em branco. Eles podem estar colados com os parenteses.

Tecnicamente, uma Lista em Lisp consiste de parenteses cercando átomos separados por espaços em branco ou cercando outras listas ou cercando os átomos e outras listas. Uma lista pode conter apenas um átomo nela ou não conter nada. Uma lista com nada se parece com isso: ~()~, e é chamada /lista vazia/. Diferentemente de todo o resto, uma lista vazia é considerada um átomo e uma lista ao mesmo tempo.

As representações impressas tanto de átomos como de listas são chamadas /expressões simbólicas/ ou, de maneira mais concisa, /s-expressions/. A palavra /expressão/ por si só pode se referir tanto para a representação impressa, como ao átomo ou como a lista já que é armazenado internamente no computador. Frequentemente, pessoas usam o termo /expressão/ indiscriminadamente. (Além disso, em muitos textos, a palavra /forma/ é utilizada como sinônimo para expressão.)

Aliás, os átomos que compõem nosso universo foram nomeados desta forma quando acreditavam ser indivisíveis; mas foi descoberto que átomos físicos não são indivisíveis. Partes podem se separa de um átomo ou ele pode fissionar em duas partes de mais ou menos mesmo tamanho. Átomos físicos foram nomeados prematuramente, antes que sua natureza verdadeira fosse descoberta. Em Lisp, alguns tipos de átomos, como um array, pode ser separado em partes; mas o mecanismo para fazer isso difere do mecanismo de separar uma lista. Até onde as operações em lista sabem, os átomos são indivisíveis.

Como em inglês, os significados das letras componentes de um átomo Lisp são diferentes do significado que as letras fazem como uma palavra. Por exemplo, a palavra para a preguiça sul-americana, '=ai=', é completamente diferente das duas palavras '=a=' e '=i='.

Existem muitos tipos de átomos na natureza mas apenas alguns em Lisp: por exemplo, /números/, como 37, 511, ou 1789, e /símbolos/, como '=+=', '=foo=' ou '~forward-line~'. As palavras que listamos nos exemplos acima são todas símbolos. Em conversas Lisp cotidianas, a palavra "átomo" não é utilizada com frequência, porque programadores geralmente tentam ser mais específicos sobre que tipo de átomo estão lidando. Programação Lisp é majoritariamente sobre símbolos (e às vezes números) dentro de listas. (Aliás, a observação precedente com três palavras entre parenteses é uma lista propriamente dita in Lisp, já que consiste de átomos, que neste caso são símbolos, separados por espaços em branco e cercados por parenteses, sem uma pontuação alheia ao Lisp.)

Texto entre aspas duplas - mesmo frases ou parágrafos - é também um átomo. Aqui está um exemplo:
#+begin_src emacs-lisp
'(essa lista possui "texto entre aspas duplas.")
#+end_src

Em Lisp, todo o texto citado acima incluindo o ponto final e espaços é um único átomo. Esse tipo de átomo é chamado de /string/ (ou cadeia de caracteres, "/string of characters/") e é o tipo de coisa que é utilizado para mensagens que um computador pode imprimir para um ser humano ler. Strings são um tipo de átomo diferente de números ou símbolos e são usadas de forma diferente
** Execute um Programa

** Gere uma Mensagem de Erro

** Nomes Símbolos e Definições de Funções

** O Interpretador Lisp

** Avaliação

** Variáveis

** Argumentos

** Assinalando o Valor de uma Variável

** Resumo

** Exercícios


* Praticando avaliação
* Como escrever definições de funções
* Algumas funções relacionadas a /buffers/
* Mais algumas funções mais complexas
* /Narrowing/ e /widening/
* ~car~, ~cdr~, ~cons~: funções fundamentais
* Recortando e armazenando texto
* Como listas são implementadas
* Colando texto de volta
* Loops e recursão
* Buscas com expressões regulares
* Contando via repetição e /regexps/
* Contando palavras em uma ~defun~
* Preparando um gráfico
* Seu arquivo ~.emacs~
** Mapeamento de teclas
* Depuração
* Conclusão
* Apêndice A
* Apêndice B
* Apêndice C
* Apêndice D
* Apêndice E
* Índice
* Sobre o autor
